#!/usr/bin/env python
# vim: ft=python

import sys
from zorpctl.Instances import ZorpHandler

results = ZorpHandler.status()
policy_not_reloaded_intances = {}
for result in results:
    if not result:
        print("STATE UNKNOWN - %s" % str(result))
        sys.exit(3)
    if not result.reloaded:
        policy_not_reloaded_intances[instance.name] = instance

amount = len(policy_not_reloaded_intances.keys()) 
if amount  == 1:
    print("WARNING - %s instance's policy not reloaded" %
                (policy_not_reloaded_intances.keys()[0]))
    sys.exit(1)

if amount > 1:
    instances = ""
    for name in policy_not_reloaded_intances.keys():
        instances += "%s " % name
    print("CRITICAL - policy is not reloaded in the following instances %s" % instances)
    sys.exit(2)

print("OK - every policy is reloaded")
sys.exit(0)
