#!/usr/bin/env python
# vim: ft=python
"""
=head1 NAME

threads - Plugin to monitor the number of threads on Linux

=head1 CONFIGURATION

No configuration

=head1 AUTHOR

Marcell Kresz

=head1 LICENSE

GNU GPL

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf
"""

import sys, os
sys.path.append(os.path.join(os.path.dirname('/etc/zorp/zorpctl/')))

import Munin

if len(sys.argv) > 1:
    if sys.argv[1] == "autoconf":
        print "yes"

    if sys.argv[1] == "config":
        print 'graph_title Number of threads'
        print 'graph_vlabel number of threads'
        print 'graph_category processes'
        print 'graph_info This graph shows the number of threads.'
        print 'threads.label threads'
        print 'threads.info The current number of threads.'
else:
    print "threads.value %d" % 200 #% Munin.sumThreads()
