#!/usr/bin/env python
# vim: ft=python

import sys
from zorpctl.Munin import *

if len(sys.argv) > 1:
    if sys.argv[1] == "config":
        print('graph_title Number of processes')
        print('graph_vlabel number of processes')
        print('graph_category zorp')
        print('graph_info This graph shows \
               the number of processes of running Zorp instances.')
        for instance in RunningInstances():
            print("%s.label %s" % (instance.name, instance.name))
else:
    for instance in RunningInstances():
        print("%s.value %d" % 
             (instance.name, instance.number_of_processes))
