#!/usr/bin/env python
# vim: ft=python

"""
=head1 NAME

sessions running - Plugin to monitor the number of running sessions in Zorp

=head1 CONFIGURATION

No configuration

=head1 AUTHOR

Marcell Kresz

=head1 LICENSE

GNU GPL

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf
"""

import sys

from zorpctl.Munin import *
from zorpctl.Instances import InstanceHandler

if len(sys.argv) > 1:
    if sys.argv[1] == "autoconf":
        print("yes")

    if sys.argv[1] == "config":
        print('graph_title Number of running sessions')
        print('graph_vlabel number of running sessions')
        print('graph_category zorp')
        print('graph_info This graph shows the number of running sessions.')
        for instance in RunningInstances():
            print("%s.label %s" % (instance.name, instance.name))

else:
    algorithm = GetSessionsRunningAlgorithm()
    for instance in RunningInstances():
        results = InstanceHandler.executeAlgorithmOnInstanceProcesses(instance, algorithm)
        sum_sessions = 0
        for result in results:
            if result:
                sum_sessions += result.value
            else:
                sum_sessions = None
                break
        if sum_sessions != None:
            print("%s.value %d" % (instance.name, sum_sessions))
        else:
            print("%s.value -1" % (instance.name))

